# Generated by Django 4.0 on 2022-09-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('ImageSlide1', models.ImageField(upload_to='5j0iq53_8jqr3')),
                ('ImageSlide2', models.ImageField(blank=True, null=True, upload_to='5j0iq53_8jqr3')),
                ('ImageSlide3', models.ImageField(blank=True, null=True, upload_to='5j0iq53_8jqr3')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
