# Generated by Django 4.0 on 2022-09-15 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_project_github_repo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='gitHub_repo',
            new_name='gitHubRepo',
        ),
    ]
