# Generated by Django 4.0 on 2022-09-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_project_projectlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lenguagesUsed',
            field=models.CharField(default='Python', max_length=200),
            preserve_default=False,
        ),
    ]
